# Generated by Django 5.1.5 on 2025-04-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('codeProjet', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nomProjet', models.CharField(max_length=40)),
                ('dateDebut', models.DateTimeField(null=True)),
                ('dateEcheanche', models.DateTimeField(null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
