# Generated by Django 5.1.5 on 2025-04-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='dateDebut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='dateEcheanche',
            field=models.DateField(null=True),
        ),
    ]
