# Generated by Django 5.1.5 on 2025-04-02 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_alter_projet_datedebut_alter_projet_dateecheanche'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousProjet',
            fields=[
                ('codeSousProjet', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nomSp', models.CharField(max_length=40)),
                ('dateDebutSp', models.DateField(null=True)),
                ('dateEcheanceSp', models.DateField(null=True)),
                ('descriptionSp', models.TextField(blank=True)),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projets.projet')),
            ],
        ),
    ]
