# Generated by Django 5.1.5 on 2025-04-02 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_sousprojet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('codeEmploye', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('courriel', models.EmailField(max_length=254, null=True, unique=True)),
                ('statut', models.CharField(choices=[('G', 'Gestionnaire'), ('E', 'Employe')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_travail', models.DateField(null=True)),
                ('heuresTravail', models.DecimalField(decimal_places=2, max_digits=4)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projets.employe')),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projets.projet')),
                ('sous_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projets.sousprojet')),
            ],
        ),
    ]
