# Generated by Django 5.1.5 on 2025-04-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_employe_worktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='Employe',
            field=models.ManyToManyField(to='projets.employe'),
        ),
    ]
