# Generated by Django 5.1.5 on 2025-04-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_projet_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='Employe',
            field=models.ManyToManyField(null=True, to='projets.employe'),
        ),
    ]
