# Generated by Django 5.1.5 on 2025-04-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0007_alter_projet_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='Employe',
            field=models.ManyToManyField(blank=True, to='projets.employe'),
        ),
    ]
