# Generated by Django 5.1.5 on 2025-04-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0008_alter_projet_employe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='Employe',
            new_name='employes',
        ),
    ]
