# Generated by Django 5.1.5 on 2025-04-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0009_rename_employe_projet_employes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='employes',
            field=models.ManyToManyField(blank=True, related_name='projets', to='projets.employe'),
        ),
    ]
