# Generated by Django 5.1.5 on 2025-04-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0010_alter_projet_employes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousprojet',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sous_projets', to='projets.projet'),
        ),
    ]
